/******************************************************************************/
/****        Generated by IBExpert 2015.12.21.1 27/07/2025 22:02:05        ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'C:\BancoSisandUsuarios\BancoSisandUsuarios.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE USUARIOS (
    ID         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NOME       VARCHAR(100) NOT NULL,
    EMAIL      VARCHAR(100) NOT NULL,
    SENHAHASH  VARCHAR(255) NOT NULL
);



/******************************************************************************/
/****                       Autoincrement generators                       ****/
/******************************************************************************/

ALTER TABLE USUARIOS ALTER ID RESTART WITH 1;

/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE USUARIOS ADD PRIMARY KEY (ID);

/******************************************************************************/
/****                          Inserir Valor Teste                         ****/
/******************************************************************************/

INSERT INTO USUARIOS (NOME, EMAIL, SENHAHASH)
VALUES ('admin', 'admin@admin.com', 'admin');